eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8000/eureka/
server:
  port: 8300
spring:
  application:
    name: client-zuul
zuul:
  routes:
    client-1:
      path: /api-1/**
      serviceId: client-1
    client-2:
      path: /api-2/**
      serviceId: client-2