eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8000/eureka/
server:
  port: 8200
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/jinse95/SpringcloudConfig
          search-paths: respo
          default-label: master


#    http请求地址和资源文件映射如下:
#    /{application}/{profile}[/{label}]
#    /{application}-{profile}.yml
#    /{label}/{application}-{profile}.yml
#    /{application}-{profile}.properties
#    /{label}/{application}-{profile}.properties
