
server:
  port: 8200
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/tripleJ1995/SpringcloudConfig
          search-paths: respo
          default-label: master
  application:
    name: config-server


#    http请求地址和资源文件映射如下:
#    /{application}/{profile}[/{label}]
#    /{application}-{profile}.yml
#    /{label}/{application}-{profile}.yml
#    /{application}-{profile}.properties
#    /{label}/{application}-{profile}.properties
